# Manually build the project and run any configured tests.
# Build only on Linux using the the lastest LTS java version
# and make the artifact available for including in a release.

name: release
on: workflow_dispatch

jobs:
  build:
    env:
      java-version: 21
      java-distribution: zulu
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{env.java-version}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.java-version}}
          distribution: ${{env.java-distribution}}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/